apiVersion: v1
kind: Secret
metadata:
  name: medicalink-secrets
  namespace: medicalink
type: Opaque
stringData:
  # Database Connection
  DATABASE_URL: "postgresql://medicalink:CHANGE_ME@/medicalink?host=/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME"
  
  # Redis Connection
  REDIS_HOST: "10.x.x.x"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_USERNAME: "default"
  REDIS_DB: "0"
  
  # RabbitMQ Connection
  RABBITMQ_URL: "amqp://admin:CHANGE_ME@rabbitmq:5672"
  
  # JWT Secrets (generate with: openssl rand -base64 32)
  JWT_ACCESS_SECRET: "CHANGE_ME_GENERATE_SECURE_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_ME_GENERATE_SECURE_SECRET"
  
  # SMTP Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASS: "your-app-password"
  
  # Super Admin
  SUPER_ADMIN_EMAIL: "admin@medicalink.com"
  SUPER_ADMIN_PASSWORD: "CHANGE_ME_SECURE_PASSWORD"
  SUPER_ADMIN_FULL_NAME: "Super Administrator"
