# Content Service
services:
  # Content Service
  content-service:
    build:
      context: ..
      dockerfile: apps/content-service/Dockerfile
    container_name: medicalink-content
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - CONTENT_SERVICE_PORT=3004
    networks:
      - medicalink-network
    command: ["node", "dist/apps/content-service/main.js"]
    restart: unless-stopped
    # Resource limits to prevent VM freeze
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Additional limits for non-swarm mode
    mem_limit: 512m
    cpus: 0.5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    # Logging Configuration - GCP Cloud Logging
    logging:
      driver: gcplogs
      options:
        gcp-project: "medicalink-06"
        gcp-log-cmd: "true"
        gcp-meta-zone: "asia-southeast1-a"
        gcp-meta-name: "medicalink-content"
        labels: |
          service=content-service
          environment=production
          component=microservice

networks:
  medicalink-network:
    external: true