# API Gateway Service
services:
  # API Gateway
  api-gateway:
    build:
      context: ..
      dockerfile: apps/api-gateway/Dockerfile
    container_name: medicalink-gateway
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - API_GATEWAY_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - medicalink-network
    command: ["node", "dist/apps/api-gateway/main.js"]
    restart: unless-stopped
    
    # Logging Configuration - GCP Cloud Logging
    logging:
      driver: gcplogs
      options:
        gcp-project: "medicalink-06"
        gcp-log-cmd: "true"
        gcp-meta-zone: "asia-southeast1-a"
        gcp-meta-name: "medicalink-gateway"
        labels: |
          service=api-gateway
          environment=production
          component=microservice

networks:
  medicalink-network:
    external: true