# Content Service
services:
  # Content Service
  content-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: medicalink-content
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - CONTENT_SERVICE_PORT=3004
    networks:
      - medicalink-network
    command: ["node", "dist/apps/content-service/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true