# Booking Service
services:
  # Booking Service
  booking-service:
    build:
      context: ..
      dockerfile: apps/booking-service/Dockerfile
    container_name: medicalink-booking
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - BOOKING_SERVICE_PORT=3003
      - DEBUG=prisma:client,prisma:engine
    networks:
      - medicalink-network
    command: ["node", "dist/apps/booking-service/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true