# Docker Compose Override for Local Development
# This file allows local development with build context while production uses images from GHCR
# Usage: docker compose -f deployment/docker-compose.yml -f deployment/docker-compose.override.yml up

services:
  # Override to use build context for local development
  # In production, these will be overridden by deployment scripts to use GHCR images
  
  api-gateway:
    build:
      context: ..
      dockerfile: apps/api-gateway/Dockerfile
    command: ["node", "dist/apps/api-gateway/main.js"]

  accounts-service:
    build:
      context: ..
      dockerfile: apps/accounts-service/Dockerfile
    command: ["node", "dist/apps/accounts-service/main.js"]

  provider-service:
    build:
      context: ..
      dockerfile: apps/provider-directory-service/Dockerfile
    command: ["node", "dist/apps/provider-directory-service/main.js"]

  booking-service:
    build:
      context: ..
      dockerfile: apps/booking-service/Dockerfile
    command: ["node", "dist/apps/booking-service/main.js"]

  content-service:
    build:
      context: ..
      dockerfile: apps/content-service/Dockerfile
    command: ["node", "dist/apps/content-service/main.js"]

  notification-service:
    build:
      context: ..
      dockerfile: apps/notification-service/Dockerfile
    command: ["node", "dist/apps/notification-service/main.js"]

  orchestrator-service:
    build:
      context: ..
      dockerfile: apps/orchestrator-service/Dockerfile
    command: ["node", "dist/apps/orchestrator-service/main.js"]
