# Accounts Service
services:
  # Accounts Service
  accounts-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicalink-accounts
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - ACCOUNTS_SERVICE_PORT=3001
    networks:
      - medicalink-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["node", "dist/apps/accounts-service/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true