# Orchestrator Service
services:
  # Orchestrator Service
  orchestrator-service:
    build:
      context: ..
      dockerfile: apps/orchestrator-service/Dockerfile
    container_name: medicalink-orchestrator
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - ORCHESTRATOR_SERVICE_PORT=3006
    networks:
      - medicalink-network
    command: ["node", "dist/apps/orchestrator-service/main.js"]
    restart: unless-stopped
    logging:
      driver: gcplogs
      options:
        gcp-project: "medicalink-06"
        gcp-log-cmd: "true"
        labels: "service,environment,component"
        env: "NODE_ENV,APP_NAME"

networks:
  medicalink-network:
    external: true