# Orchestrator Service
services:
  # Orchestrator Service
  orchestrator-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicalink-orchestrator
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - ORCHESTRATOR_SERVICE_PORT=3006
    networks:
      - medicalink-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["node", "dist/apps/orchestrator-service/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true