# API Gateway Service
services:
  # API Gateway
  api-gateway:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: medicalink-gateway
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - API_GATEWAY_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - medicalink-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["node", "dist/apps/api-gateway/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3