# Accounts Service
services:
  # Accounts Service
  accounts-service:
    build:
      context: ..
      dockerfile: apps/accounts-service/Dockerfile
    container_name: medicalink-accounts
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - ACCOUNTS_SERVICE_PORT=3001
    networks:
      - medicalink-network
    command: ["node", "dist/apps/accounts-service/main.js"]
    restart: unless-stopped
    
    # Logging Configuration - GCP Cloud Logging
    logging:
      driver: gcplogs
      options:
        gcp-project: "medicalink-06"
        gcp-log-cmd: "true"
        gcp-meta-zone: "asia-southeast1-a"
        gcp-meta-name: "medicalink-accounts"
        labels: |
          service=accounts-service
          environment=production
          component=microservice

networks:
  medicalink-network:
    external: true