# Notification Service
services:
  # Notification Service
  notification-service:
    build:
      context: ..
      dockerfile: apps/notification-service/Dockerfile
    container_name: medicalink-notification
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - NOTIFICATION_SERVICE_PORT=3005
    networks:
      - medicalink-network
    command: ["node", "dist/apps/notification-service/main.js"]
    restart: unless-stopped

networks:
  medicalink-network:
    external: true