export const ErrorCode = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  INFRA_UNAVAILABLE: 'INFRA_UNAVAILABLE',
  UNIQUE_VIOLATION: 'P2002',
  RECORD_NOT_FOUND: 'P2025',
  UNEXPECTED: 'UNEXPECTED',
  // Permission-specific error codes
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  USER_PERMISSION_NOT_FOUND: 'USER_PERMISSION_NOT_FOUND',
  GROUP_PERMISSION_NOT_FOUND: 'GROUP_PERMISSION_NOT_FOUND',
  USER_GROUP_MEMBERSHIP_NOT_FOUND: 'USER_GROUP_MEMBERSHIP_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  GROUP_ALREADY_EXISTS: 'GROUP_ALREADY_EXISTS',
  USER_PERMISSION_ALREADY_EXISTS: 'USER_PERMISSION_ALREADY_EXISTS',
  GROUP_PERMISSION_ALREADY_EXISTS: 'GROUP_PERMISSION_ALREADY_EXISTS',
  USER_GROUP_MEMBERSHIP_ALREADY_EXISTS: 'USER_GROUP_MEMBERSHIP_ALREADY_EXISTS',
  DEFAULT_GROUP_CANNOT_BE_DELETED: 'DEFAULT_GROUP_CANNOT_BE_DELETED',
  DEFAULT_GROUP_CANNOT_BE_RENAMED: 'DEFAULT_GROUP_CANNOT_BE_RENAMED',
  INVALID_PERMISSION_CONDITION: 'INVALID_PERMISSION_CONDITION',
  PERMISSION_EVALUATION_FAILED: 'PERMISSION_EVALUATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
