export const ErrorCode = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  INFRA_UNAVAILABLE: 'INFRA_UNAVAILABLE',
  UNIQUE_VIOLATION: 'P2002',
  RECORD_NOT_FOUND: 'P2025',
  UNEXPECTED: 'UNEXPECTED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
